### PR TITLE
Added `alloc.hpp` to `CMakeLists.txt` of base dir

### LINKED ISSUE #390: `graphblas/alloc.hpp: No such file or directory` on compile example
When trying to follow the instructions under _very quick start_:
```
cd <ALP/root/dir>
mkdir build
cd build
../bootstrap.sh --prefix=../install
make -j
make -j install
source ../install/bin/setenv
grbcxx ../examples/sp.cpp
grbrun ./a.out
```
The following error appears:
```
In file included from /tmp/ALP/install/include/graphblas/vector.hpp:32,
                 from /tmp/ALP/install/include/graphblas.hpp:527,
                 from ../examples/sp.cpp:36:
[...]/include/graphblas/reference/vector.hpp:50:10: fatal error: graphblas/alloc.hpp: No such file or directory
   50 | #include <graphblas/alloc.hpp>

```
Probably caused by #383

### PR DESCRIPTION
**Pull request by GiovaGa**
Solves #390

### CODE REVIEW

**Review by anyzelman — APPROVED** [review]

**Comment by anyzelman** [comment]
Fix manually checked to resolve #390 . Code review OK. After CI OK, will merge.

Note: also raised #392 to have an automated check for this and similar issues in future.
