### ISSUE TITLE
`graphblas/alloc.hpp: No such file or directory` on compile example

### ISSUE THREAD

**Issue by GiovaGa** [Algebraic-Programming/ALP#390]
When trying to follow the instructions under _very quick start_:
```
cd <ALP/root/dir>
mkdir build
cd build
../bootstrap.sh --prefix=../install
make -j
make -j install
source ../install/bin/setenv
grbcxx ../examples/sp.cpp
grbrun ./a.out
```
The following error appears:
```
In file included from /tmp/ALP/install/include/graphblas/vector.hpp:32,
                 from /tmp/ALP/install/include/graphblas.hpp:527,
                 from ../examples/sp.cpp:36:
[...]/include/graphblas/reference/vector.hpp:50:10: fatal error: graphblas/alloc.hpp: No such file or directory
   50 | #include <graphblas/alloc.hpp>

```
Probably caused by #383

**Comment by GiovaGa** [comment]
The example works for 1414c499
